name: Development workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: root

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run build --if-present

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.PB0JWSkfqeaBelWmBZGW96LP8w36B3oCHKNu55m1VVo }}
          NETLIFY_HOOK_ID: ${{ secrets.6383a667a04cfb295ae70774 }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_HOOK_ID"]'
